name: Listar Problemas no Markdown

on:
  push:
    branches: [master]

jobs:
  atualizar_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Atualizar Codigos
        run: sh doc.sh > README.md

      - name: Criar Commit Atualizado
        run: |
          git config --local user.email "wesleykaihara@gmail.com"
          git config --local user.name "Wesley"
          git add README.md
          git commit -m "Listagem dos problemas"

      - name: Enviar Novo README
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
